# 毎朝 00:00 UTC（JST 9:00）に自動実行＋手動実行も可能
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 line-bot-sdk python-dotenv

    - name: Fetch grants and store to DB
      run: python fetch_grants.py

    - name: Push LINE notifications
      env:
        LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        LINE_CHANNEL_SECRET:       ${{ secrets.LINE_CHANNEL_SECRET }}
      run: python notify_grants.py
