name: SubsidyBot Daily Notify

on:
  schedule:
    # UTC 0:00 → 日本時間 9:00 に動く
    - cron: '0 0 * * *'
  workflow_dispatch:   # 手動実行もできるように

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 line-bot-sdk

      - name: Fetch grants
        run: python fetch_grants.py

      - name: Notify grants
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_CHANNEL_SECRET:       ${{ secrets.LINE_CHANNEL_SECRET }}
        run: python notify_grants.py
